{% set name = "panel-jstree" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-jstree-{{ version }}.tar.gz
  sha256: 784907e9411cdc95fe25bdab9f910ce598188ab5d9d6c1a3c4b3f71118215a1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - panel >1

test:
  imports:
    - panel_jstree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/madeline-scyphers/panel-jstree
  summary: This package makes it super simple to do exploratory data analysis and develop high-quality Panel data apps ...
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - madeline-scyphers
