{% set name = "panel-jstree" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-jstree-{{ version }}.tar.gz
  sha256: 49ddd76fc3e292ef14bfcef8e6d4c7dc72cf29209f434f5cf4d5999c3eeb3ec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - panel >1

test:
  imports:
    - panel_jstree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/madeline-scyphers/panel-jstree
  summary: panel-jstree is a wrapper python wrapper around the javascript library jstree for use in panel. This allows for JSON-like representations of tree data. One very useful implementation provided is a server-side file browser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - madeline-scyphers
