{% set name = "panel-jstree" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-jstree-{{ version }}.tar.gz
  sha256: 0bff000f4c14668624b89ae5b5b6fa2908e41453aeaf43658ac9a2b05431b22f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - panel >1.3

test:
  imports:
    - panel_jstree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/madeline-scyphers/panel-jstree
  summary: panel-jstree is a wrapper python wrapper around the javascript library jstree for use in panel. This allows for JSON-like representations of tree data. One very useful implementation provided is a server-side file browser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - madeline-scyphers
